- travis-tools/travis_setup.sh
- needed to properly compile binary gems
- the overhead for plain Ruby gems is small, it can be installed always
(the package size is ~1.5MB)
> install "ruby-dev" before installing Ruby gems

- travis-tools/travis_setup.sh
- needed to properly compile binary gems
- the overhead for plain Ruby gems is small, it can be installed always
(the package size is ~1.5MB)
> Install "ruby-dev" before installing Ruby gems (SLE12)

- .gitignore
- build-tools/Makefile.am.toplevel
- build-tools/scripts/y2autoconf
- configure.in.in
- package/yast2-devtools.changes
- package/yast2-devtools.spec
* replace obsolete `A[CM]_PROG_LIBTOOL` with `LT_INIT()`
```
Macro: LT_INIT (options)
AC_PROG_LIBTOOL and AM_PROG_LIBTOOL are deprecated names
for older versions of this macro.
```
See [GNU Libtool Manual](http://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html).
* use new `AC_INIT()`-syntax with args in square braces
They are important to ensure that GNU m4 parses the configure.ac file correctly.
See [GNU Autoconf Manual](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Initializing-configure.html#Initializing-configure).
> get GNU Autotools up-to-date

- build-tools/rpm/macros.yast
- build-tools/scripts/y2autoconf
- package/yast2-devtools.changes
- package/yast2-devtools.spec
As the title says.  There is no change in default behaviour. I just added an option to include "-DNDEBUG" by configure-switch in addtion to pass it from $ENV's C(XX)FLAGS.
> add configure-option '--disable-debug'

- build-tools/scripts/y2makepot
- package/yast2-devtools.changes
- package/yast2-devtools.spec
they cause for example rubocop check to fail
- 3.1.36
> y2makepot: do not create confusing _MISSING_TEXTDOMAIN_* files

- package/yast2-devtools.changes
- package/yast2-devtools.spec
- ytools/y2tool/rubocop_yast_style.yml
- Integrated the common SUSE style from https://github.com/SUSE/style-guides/blob/master/rubocop-suse.yml file
- 3.1.37
Note: It's basicaly the shared file with some extra rules at the end of the file. The only change is that I disabled (commented out) the new `Lint/EndAlignment` check as it would report too many issues in the current YaST code. (We could enable it later after discussing it when needed.)
I have tested several YaST modules and the new file is OK, no regressions.
> Integrate the common rubocop.yml file for the SUSE Ruby style

- build-tools/rpm/macros.yast
- package/yast2-devtools.changes
- package/yast2-devtools.spec
Some packages use the new `configure.ac.in` file instead of the old `configure.in.in`.
> Added a check for configure.ac.in file

- build-tools/rpm/macros.yast
Tested with yast2-nfs-client:
- Build devtools using `rake osc:build['-k /tmp/RPMS']`
- Build yast2-nfs-client ([`jenkins_spupport` branch](https://github.com/yast/yast-nfs-client/compare/jenkins_support?expand=1)) using `rake osc:build['-p /tmp/RPMS --with=yast_run_ci_tests']`
Then rubocop was called during the RPM build.
> Run the extra Jenkins checks also for the autotools based packages

- build-tools/scripts/control_to_glade.xsl
- package/yast2-devtools.changes
- package/yast2-devtools.spec
This is needed so that the comments added in https://github.com/yast/skelcd-control-SLES/pull/54 actually reach their audience.
Part of https://trello.com/c/0mOtUy45/467-8-sle-12-sp2-p4-m-feature-317481-add-system-role-capabilities-to-installer
> y2makepot: copy also comments for translators from control.xml

- package/yast2-devtools.changes
- package/yast2-devtools.spec
- ytools/y2tool/rubocop_yast_style.yml
to make it work with Rubocop 0.40.0
> Update the Rubocop config

- ytools/yast2/create_maintenance_branch
There is Rakefiles which have copyright header, in such case, it is
placed after line which require "yast/rake" resulting in exception that
Yast::Tasks do not exists.
> more precisely place submit_to line

- travis-tools/travis_setup.sh
Added support for the new distributions at Travis.
This fix should make https://github.com/yast/yast-migration/pull/37 green.
> Travis support for SLE12-SP[1-3]

- build-tools/aclocal/y2autoconf.m4
- build-tools/rpm/macros.yast
- build-tools/scripts/y2autoconf
- package/yast2-devtools.changes
- package/yast2-devtools.spec
The new path for fillup-templates is `/usr/share/fillup-templates`.
> Fix fillup-templates path

- build-tools/scripts/gettextdomains
- package/yast2-devtools.changes
- package/yast2-devtools.spec
This is a fix for the script building the POT files.
- The yast-storage-ng code contains a translatable string with interpolation (that's wrong), see [here](https://github.com/yast/yast-storage-ng/blob/e2da188b8d3b39c79028cdd99738b6518ee00da2/src/lib/y2storage/actions_presenter.rb#L107-L110)
- But that text is not found as the script considers the `#{}` interpolation as a comment line (due to `#`) and ignores the line
- Because that file does not contain another translatable string the whole file is ignored
- Because the text is missing in *.pot the `rake check:pot` does not find the issue with the interpolation
Proposed fix
- Do not treat lines with `#{` as comments
- This is not a 100% solution but we would need a full parser instead of "simple" regexps
> Do not treat Ruby string interpolations as comments

- build-tools/scripts/gettextdomains
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- The script skipped all XML files because no gettext call was found
- The XML files do not contain any `_()` or `gettext()` markers, there is `<label>` tag used instead
- With this fix `control.pot` is correctly generated again for `skelcd-control-openSUSE` and others
- 4.0.4
> Fixed generating translations from XML files (bsc#1083015)

- build-tools/scripts/control_to_glade.xsl
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- See https://bugzilla.suse.com/show_bug.cgi?id=1083720
- A XSL file is basically a XML file, we just need to handle the different root element
- 4.0.5
> Extract the translatable texts from XSL files (bsc#1083720)

- build-tools/aminclude/autodocs-ycp.ami
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- Pass absolute paths to "yard", relative paths do not work anymore because of a recent  security update
- Almost all YaST packages in https://build.suse.de/project/monitor/Devel:YaST:SLE-12-SP1 fail to build in the SLE-12-SP1_Update target
- See https://bugzilla.suse.com/show_bug.cgi?id=1070263
- 3.1.38.1
Note: we stopped generating the autodocs in SP2+ so we need to release the fix only for SP1.
Originally the relative path was used:
```
yard doc --title "yast2-snapper -- Development Documentation" -o . -m markdown ./../../
src/modules/SnapperDbus.rb ./../../src/modules/Snapper.rb ./../../src/include/snapper/d
ialogs.rb ./../../src/include/snapper/helps.rb ./../../src/include/snapper/wizards.rb
```
But that fails now because the relative prefix is removed:
``` …
```
> Pass absolute paths to "yard"

- build-tools/scripts/y2autoconf
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- Fix for the previous PR #135, installation failed because of unexpanded `@icondir@`:
`/usr/bin/install -c -p -m 644 icons/hicolor/scalable/apps/yast-audit-laf.svg '@icondir@/hicolor/scalable/apps'`
- 4.1.2
> Fix up for the icondir path expansion (boo#1109310)

- build-tools/aclocal/y2autoconf.m4
- build-tools/rpm/macros.yast
- build-tools/scripts/Makefile.am
- build-tools/scripts/y2metainfo
- package/yast2-devtools.changes
- package/yast2-devtools.spec
https://features.opensuse.org/319035 "Make YaST (incl. modules) available in GNOME Software"
> Generate metainfo for desktop files

- build-tools/rpm/macros.yast
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- Fixed syntax error in the RPM macros causing ``line 53: [: missing `]'`` error during package build
- Found accidentally in this [Travis log](https://travis-ci.org/yast/yast-country/builds/546694483#L1187)
- Related to the desktop file changes ([boo#1084864](https://bugzilla.opensuse.org/show_bug.cgi?id=1084864))
- 4.2.5
> Fixed syntax error in the RPM macros

- .travis.yml
- ytools/yast2/create_maintenance_branch
- Added `--dry-run` option to skip committing the changes, you can review them
- Adapted Dockerfile for new OBS images
- Fixed regexp for finding the existing branch (it complained that the branch existed if e.g. `SLE-15-SP2-test` was present)
- Reformatted by Rubocop
> Updated branching script

- build-tools/scripts/y2metainfo
Continuation to https://github.com/yast/yast-control-center/pull/43
Appstream builder now has to be able to find the `.desktop` version of ycc and other modules. It also rejects anything containing the listed categories.
> Supplement changes from YCC

- build-tools/rpm/macros.yast
Order is important for find. Swapped -name and -print0
> Fixed order in %yast_desktop_files macro

- build-tools/rpm/Makefile.am
- package/yast2-devtools.changes
- package/yast2-devtools.spec
The package yast2-buildtools installs the YaST macros in **/etc/rpm/macros.yast**
As reported in the bug RPM packages though are supposed to install their macro files to **/usr/lib/rpm/macros.d** (use the variable %{_rpmmacrodir})
- https://bugzilla.suse.com/show_bug.cgi?id=1189044
Apply suggested change
> Install yast macros to %{_rpmmacrodir}

- package/yast2-devtools.changes
- package/yast2-devtools.spec
- ytools/y2tool/Makefile.am
- ytools/y2tool/rubocop-1.24.1_yast_style.yml
changes to previous config will be added as inline comment to this PR
> add new shared rubocop config

- build-tools/scripts/control_to_glade.xsl
- package/yast2-devtools.changes
- package/yast2-devtools.spec
https://bugzilla.suse.com/show_bug.cgi?id=1197965
The translatable messages from XML contain surrounding white space in the generated POT file. However, when YaST parses the XML it [trims the white space away](https://github.com/yast/yast-yast2/blob/b3cc5ae199cdf74fca0f4567bc08f4cebc722773/library/xml/src/modules/XML.rb#L256). That might cause a mismatch between the original text and the translations, the result is that these messages are displayed untranslated.
Trim the leading and trailing white space from the messages when generating the POT files. Then the POT messages will match what YaST will read from the XML file.
For testing I used the [yast-firstboot/firstboot.xml](https://github.com/yast/yast-firstboot/blob/master/wsl/firstboot.xml) file which contains this snippet with a …
> Fixed generating POT files from XML (bsc#1197965)

- build-tools/scripts/control_to_glade.xsl
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- Fix up for #164 
- We need to trim also the tabs
Tested with skelcd-control-openSUSE
```diff
#: control/control.openSUSE.glade.translations.glade:23
-msgid ""
-"Graphical system with GNOME as desktop environment. Suitable for Workstations, Desktops and Laptops.\n"
-"\t"
+msgid "Graphical system with GNOME as desktop environment. Suitable for Workstations, Desktops and Laptops."
msgstr ""
```
> Trim also the tabs (bsc#1197965)

- build-tools/scripts/Makefile.am
- build-tools/scripts/gettextdomains
- build-tools/scripts/qt_ui.its
- build-tools/scripts/y2makepot
- package/yast2-devtools.changes
- package/yast2-devtools.spec
- https://github.com/libyui/libyui/pull/74
- The texts from Qt `*.ui` files were not included in the POT file
- Lets add support Qt designer files, fortunately these are XML so the solution is similar to YaST the control file support.
- Tested manually
`y2makepot` finds the texts in libyui-qt:
```pot
#: src/QStyleEditor.ui:26
msgid "&Apply"
msgstr ""
#: src/QStyleEditor.ui:36
msgid "Auto Apply"
msgstr ""
#: src/QStyleEditor.ui:66
msgid "&Load File"
msgstr ""
```
See also related https://github.com/libyui/libyui/pull/75
> y2makepot - extract translatable string from Qt designer *.ui files

- package/yast2-devtools.changes
- package/yast2-devtools.spec
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
Rubocop change is not needed in SP6, so lets just skip version and bump to non colliding version.
> Backport SP6

- package/yast2-devtools.changes
- package/yast2-devtools.spec
- ytools/y2tool/rubocop-0.71.0_yast_style.yml
- ytools/y2tool/rubocop-1.24.1_yast_style.yml
- The submit to SP7 https://build.suse.de/request/show/343961 has been rejected because the change reverts last fix
- For some reason the change https://github.com/yast/yast-devtools/pull/171 was submitted to SP6 without merging to the SP6 Git branch. :scream: 
- Let's synchronize the Git version to version in OBS.
> Merge change from OBS SP6 to Git

- package/yast2-devtools.changes
- package/yast2-devtools.spec
Add `which` to the list of dependencies because it is used by some scripts like `y2makepot`.
> fix: add "which" to the list of dependencies
